source 'https://git.coding.net/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ELASTOS_RN_FRAMEWORK' do
  pod 'AFNetworking', '~> 2.0'

end
